import { createSlice } from "@reduxjs/toolkit";
import p1 from "../../assets/product-1.svg";
import p2 from "../../assets/product-2.svg";
import p3 from "../../assets/product-3.svg";
import p4 from "../../assets/product-4.svg";
import p5 from "../../assets/product-5.svg";
export const initialState = [
  {
    src: p1,
    title: "Graphic Design",
    description: "English Department",
    price: 6.48,
    original_price: 16.48,
    showColors: true,
    category: "Women's clothing",
    brand: "Zara",
  },
  {
    src: p2,
    title: "Graphic Design",
    description: "English Department",
    price: 6.48,
    original_price: 16.48,
    showColors: true,
    category: "Women's clothing",
    brand: "Zara",
  },
  {
    src: p3,
    title: "Graphic Design",
    description: "English Department",
    price: 6.48,
    original_price: 16.48,
    showColors: true,
    category: "Women's clothing",
    brand: "Levi's",
  },
  {
    src: p4,
    title: "Graphic Design",
    description: "English Department",
    price: 6.48,
    original_price: 16.48,
    showColors: true,
    category: "Kid's Clothing",
    brand: "Levi's",
  },
  {
    src: p5,
    title: "Graphic Design",
    description: "English Department",
    price: 6.48,
    original_price: 16.48,
    showColors: true,
    category: "Kid's clothing",
    brand: "Adidas",
  },
  {
    src: p1,
    title: "Graphic Design",
    description: "English Department",
    price: 6.48,
    original_price: 16.48,
    showColors: true,
    category: "Footwear",
    brand: "Adidas",
  },
  {
    src: p2,
    title: "Graphic Design",
    description: "English Department",
    price: 6.48,
    original_price: 16.48,
    showColors: true,
    category: "Footwear",
    brand: "Adidas",
  },
  {
    src: p3,
    title: "Graphic Design",
    description: "English Department",
    price: 6.48,
    original_price: 16.48,
    showColors: true,
    category: "Watches",
    brand: "Peter England",
  },
  {
    src: p4,
    title: "Graphic Design",
    description: "English Department",
    price: 6.48,
    original_price: 16.48,
    showColors: true,
    category: "Watches",
    brand: "Peter England",
  },
  {
    src: p5,
    title: "Graphic Design",
    description: "English Department",
    price: 6.48,
    original_price: 16.48,
    showColors: true,
    category: "Watches",
    brand: "Allen Solly",
  },

  {
    src: p5,
    title: "Graphic Design",
    description: "English Department",
    price: 6.48,
    original_price: 16.48,
    showColors: true,
    category: "Beauty",
    brand: "Allen Solly",
  },
  {
    src: p4,
    title: "Graphic Design",
    description: "English Department",
    price: 6.48,
    original_price: 16.48,
    showColors: true,
    category: "Beauty",
    brand: "Fab India",
  },
  {
    src: p3,
    title: "Graphic Design",
    description: "English Department",
    price: 6.48,
    original_price: 16.48,
    showColors: true,
    category: "Beauty",
    brand: "Fab India",
  },
  {
    src: p2,
    title: "Graphic Design",
    description: "English Department",
    price: 6.48,
    original_price: 16.48,
    showColors: true,
    category: "Handbags",
    brand: "Peter England",
  },
  {
    src: p1,
    title: "Graphic Design",
    description: "English Department",
    price: 6.48,
    original_price: 16.48,
    showColors: true,
    category: "Handbags",
    brand: "Peter England",
  },
  {
    src: p5,
    title: "Graphic Design",
    description: "English Department",
    price: 6.48,
    original_price: 16.48,
    showColors: true,
    category: "Handbags",
    brand: "Levi's",
  },
  {
    src: p4,
    title: "Graphic Design",
    description: "English Department",
    price: 6.48,
    original_price: 16.48,
    showColors: true,
    category: "Jwellery",
    brand: "Levi's",
  },
  {
    src: p3,
    title: "Graphic Design",
    description: "English Department",
    price: 6.48,
    original_price: 16.48,
    showColors: true,
    category: "Jwellery",
    brand: "Adidas",
  },
  {
    src: p2,
    title: "Graphic Design",
    description: "English Department",
    price: 6.48,
    original_price: 16.48,
    showColors: true,
    category: "Jwellery",
    brand: "Adidas",
  },
  {
    src: p1,
    title: "Graphic Design",
    description: "English Department",
    price: 6.48,
    original_price: 16.48,
    showColors: true,
    category: "Jwellery",
    brand: "Adidas",
  },
];

const productSlice = createSlice({
  name: "product",
  initialState,
  reducers: {},
});

export default productSlice.reducer;
