import { createSlice } from "@reduxjs/toolkit";
import p1 from "../../assets/product-1.svg";
import p2 from "../../assets/product-2.svg";
import p3 from "../../assets/product-3.svg";
import p4 from "../../assets/product-4.svg";
import p5 from "../../assets/product-5.svg";
export const initialState = [
  {
    id: "p1",
    src: p1,
    title: "Graphic Design",
    description: "English Department",
    original_price: 6.48,
    price: 16.48,
    showColors: true,
    category: "Women's clothing",
    brand: "Zara",
  },
  {
    id: "p2",
    src: p2,
    title: "Graphic Design",
    description: "English Department",
    original_price: 19.48,
    price: 16.48,
    showColors: true,
    category: "Women's clothing",
    brand: "Zara",
  },
  {
    id: "p3",
    src: p3,
    title: "Graphic Design",
    description: "English Department",
    original_price: 18.48,
    price: 16.48,
    showColors: true,
    category: "Women's clothing",
    brand: "Levi's",
  },
  {
    id: "p4",
    src: p4,
    title: "Graphic Design",
    description: "English Department",
    original_price: 24.48,
    price: 16.48,
    showColors: true,
    category: "Kid's Clothing",
    brand: "Levi's",
  },
  {
    id: "p5",
    src: p5,
    title: "Graphic Design",
    description: "English Department",
    original_price: 39.48,
    price: 16.48,
    showColors: true,
    category: "Kid's clothing",
    brand: "Adidas",
  },
  {
    id: "p6",
    src: p1,
    title: "Graphic Design",
    description: "English Department",
    original_price: 41.48,
    price: 16.48,
    showColors: true,
    category: "Footwear",
    brand: "Adidas",
  },
  {
    id: "p7",
    src: p2,
    title: "Graphic Design",
    description: "English Department",
    original_price: 12.48,
    price: 16.48,
    showColors: true,
    category: "Footwear",
    brand: "Adidas",
  },
  {
    id: "p8",
    src: p3,
    title: "Graphic Design",
    description: "English Department",
    original_price: 19.48,
    price: 16.48,
    showColors: true,
    category: "Watches",
    brand: "Peter England",
  },
  {
    id: "p9",
    src: p4,
    title: "Graphic Design",
    description: "English Department",
    original_price: 59.48,
    price: 16.48,
    showColors: true,
    category: "Watches",
    brand: "Peter England",
  },
  {
    id: "p10",
    src: p5,
    title: "Graphic Design",
    description: "English Department",
    original_price: 62.48,
    price: 16.48,
    showColors: true,
    category: "Watches",
    brand: "Allen Solly",
  },

  {
    id: "p11",
    src: p5,
    title: "Graphic Design",
    description: "English Department",
    original_price: 78.48,
    price: 16.48,
    showColors: true,
    category: "Beauty",
    brand: "Allen Solly",
  },
  {
    id: "p12",
    src: p4,
    title: "Graphic Design",
    description: "English Department",
    original_price: 61.48,
    price: 16.48,
    showColors: true,
    category: "Beauty",
    brand: "Fab India",
  },
  {
    id: "p13",
    src: p3,
    title: "Graphic Design",
    description: "English Department",
    original_price: 91.48,
    price: 16.48,
    showColors: true,
    category: "Beauty",
    brand: "Fab India",
  },
  {
    id: "p14",
    src: p2,
    title: "Graphic Design",
    description: "English Department",
    original_price: 106.48,
    price: 16.48,
    showColors: true,
    category: "Handbags",
    brand: "Peter England",
  },
  {
    id: "p15",
    src: p1,
    title: "Graphic Design",
    description: "English Department",
    original_price: 99.48,
    price: 16.48,
    showColors: true,
    category: "Handbags",
    brand: "Peter England",
  },
  {
    id: "p16",
    src: p5,
    title: "Graphic Design",
    description: "English Department",
    original_price: 102.48,
    price: 16.48,
    showColors: true,
    category: "Handbags",
    brand: "Levi's",
  },
  {
    id: "p17",
    src: p4,
    title: "Graphic Design",
    description: "English Department",
    original_price: 115.48,
    price: 16.48,
    showColors: true,
    category: "Jwellery",
    brand: "Levi's",
  },
  {
    id: "p18",
    src: p3,
    title: "Graphic Design",
    description: "English Department",
    original_price: 130.48,
    price: 16.48,
    showColors: true,
    category: "Jwellery",
    brand: "Adidas",
  },
  {
    id: "p19",
    src: p2,
    title: "Graphic Design",
    description: "English Department",
    original_price: 190.48,
    price: 16.48,
    showColors: true, 
    category: "Jwellery",
    brand: "Adidas",
  },
  {
    id: "p20",
    src: p1,
    title: "Graphic Design",
    description: "English Department",
    original_price: 159.48,
    price: 16.48,
    showColors: true,
    category: "Jwellery",
    brand: "Adidas",
  },
];

const productSlice = createSlice({
  name: "product",
  initialState,
  reducers: {},
});

export default productSlice.reducer;
